# Generated by Django 2.2 on 2020-05-03 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0045_auto_20200418_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaundryBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieveDate', models.DateField(default=datetime.date.today, null=True)),
                ('endDate', models.DateField(default=datetime.date.today, null=True)),
                ('sumtotal', models.FloatField(default=0.0, null=True)),
                ('paid', models.FloatField(default=0.0, null=True)),
                ('remain', models.FloatField(default=0.0, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Clients')),
            ],
        ),
        migrations.CreateModel(
            name='LaundryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launtype', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0, null=True)),
                ('total', models.FloatField(default=0.0, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.LaundryBill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.Customers')),
            ],
        ),
    ]
