# Generated by Django 2.2.13 on 2020-08-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_auto_20200523_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrybill',
            name='closebill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laundrybill',
            name='remaindone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laundrybill',
            name='stillremain',
            field=models.BooleanField(default=False),
        ),
    ]
