# Generated by Django 2.2 on 2019-05-11 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20190511_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfirm',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 16, 29, 10, 288033, tzinfo=utc)),
        ),
    ]
