# Generated by Django 2.2 on 2019-05-11 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190511_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfirm',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 16, 31, 50, 795944, tzinfo=utc)),
        ),
    ]
