# Generated by Django 2.2 on 2019-06-26 22:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20190626_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfirm',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2019, 6, 26, 22, 7, 2, 623943, tzinfo=utc)),
        ),
    ]
