# Generated by Django 2.2 on 2019-06-26 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20190626_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfirm',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2019, 6, 26, 22, 54, 10, 766740, tzinfo=utc)),
        ),
    ]
