# Generated by Django 2.2 on 2019-06-26 22:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20190626_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfirm',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2019, 6, 26, 22, 56, 33, 797636, tzinfo=utc)),
        ),
    ]
