# Generated by Django 2.2 on 2019-06-27 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20190627_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfirm',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 14, 4, 15, 968258, tzinfo=utc)),
        ),
    ]
