# Generated by Django 2.2 on 2019-06-28 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20190627_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfirm',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2019, 6, 28, 12, 7, 22, 954873, tzinfo=utc)),
        ),
    ]
