# Generated by Django 2.2 on 2019-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20190628_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordfirm',
            old_name='Company Name',
            new_name='firm_name',
        ),
        migrations.AlterField(
            model_name='recordfirm',
            name='last_visit',
            field=models.DateField(auto_now=True),
        ),
    ]
