# Generated by Django 2.2 on 2019-06-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20190628_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfirm',
            name='type',
            field=models.CharField(choices=[('T', 'Tax No'), ('P', 'Purchase No'), ('S', 'Others')], max_length=5, null=True),
        ),
    ]
