# Generated by Django 2.2 on 2019-06-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_recordfirm_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfirm',
            name='type',
            field=models.CharField(choices=[('E', 'Egy Pound'), ('S', 'US Dollar')], max_length=1, null=True),
        ),
    ]
