# Generated by Django 2.2 on 2019-06-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20190629_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfirm',
            name='part_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='recordfirm',
            name='purchase_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='recordfirm',
            name='tax_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='recordfirm',
            name='type',
            field=models.CharField(choices=[('EGY', 'Egy Pound'), ('USD', 'US Dollar')], max_length=3, null=True),
        ),
    ]
