# Generated by Django 2.2 on 2019-06-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_auto_20190629_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='recordfirm',
            name='part_no',
        ),
        migrations.RemoveField(
            model_name='recordfirm',
            name='purchase_no',
        ),
        migrations.RemoveField(
            model_name='recordfirm',
            name='tax_no',
        ),
        migrations.AddField(
            model_name='recordfirm',
            name='paper',
            field=models.ManyToManyField(to='crm.Choices'),
        ),
    ]
