# Generated by Django 2.2 on 2019-06-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_auto_20190629_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfirm',
            name='part_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordfirm',
            name='purchase_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordfirm',
            name='tax_no',
            field=models.BooleanField(default=False),
        ),
    ]
