# Generated by Django 2.2.2 on 2019-07-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_auto_20190704_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfirm',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Clients'),
        ),
    ]
