# Generated by Django 2.2.2 on 2019-07-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_remove_recordfirm_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfirm',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Clients'),
        ),
    ]
