# Generated by Django 2.2.2 on 2019-07-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_recordfirm_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordfirm',
            name='firm_name',
        ),
    ]
