# Generated by Django 2.2.2 on 2019-07-11 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_remove_recordfirm_firm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfirm',
            name='client',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Clients'),
        ),
    ]
