# Generated by Django 2.2.2 on 2019-07-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_auto_20190711_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfirm',
            name='client',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='crm.Clients'),
        ),
    ]
