# Generated by Django 2.2.2 on 2019-07-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_auto_20190711_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfirm',
            name='Company Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
