# Generated by Django 2.2.2 on 2019-07-15 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_recordfirm_company name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfirm',
            name='client_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='crm.Clients'),
        ),
    ]
