# Generated by Django 2.2 on 2020-04-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_auto_20190715_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='_notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='identityNo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Clients_pics'),
        ),
    ]
