# Generated by Django 2.2 on 2020-04-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_auto_20200415_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='photo',
            field=models.ImageField(blank=True, upload_to='crm/Clients_pics'),
        ),
    ]
